### PR TITLE
Move files to .tmpl so they are hidden from IDEs

### LINKED ISSUE #9: Page and PageController show up in IDEs as valid classes
When using an IDE's "find class" feature, Page and PageController will often match two different files (the one in the project and the one in recipe-cms).

Please can we rename the files to have an extension like `.tmpl` or whatnot so that IDEs don't recognise them as PHP classes.

When we copy the files into projects we can copy and rename them instead to just copying them.

### PR DESCRIPTION
**Pull request by dhensby**
Dpends on https://github.com/silverstripe/recipe-plugin/pull/5

Fixes #9

### CODE REVIEW

**Comment by robbieaverill** [comment]
I think we need to revisit this. It's starting to cause Travis build failures, e.g. https://travis-ci.org/silverstripe/silverstripe-siteconfig/jobs/441636404#L767-L770 (disclaimer: I _think_ it's related anyway)

**Comment by dhensby** [comment]
Feel free to take it over; it's a massive pain, I found ;)

**Comment by maxime-rainville** [comment]
Is this still relevant? If it's actually causing us problems, then maybe we should have a proper issue to track it.

**Comment by robbieaverill** [comment]
Yep still relevant:

image

image

**Comment by robbieaverill** [comment]
Agree let's create an issue to track this

**Comment by robbieaverill** [comment]
Oh the issue is #9 - haha

**Comment by maxime-rainville** [comment]
Sorry I had a brain fart there.

**Comment by unclecheese** [comment]
@dhensby  This was automatically closed because it was targeted against an EOL branch. Can you please rebase against 1.2 and retarget? (1.2 is EOL in 11 days, FYI)

**Pull request closed without merging**
